services:
  board-sse-linuxfr.og:
    build:
      context: .
      dockerfile: ./deployment/Containerfile
    env_file:
      - deployment/default.env
    depends_on:
      - redis

  redis:
    image: redis:5
    volumes:
      - data-redis:/data

volumes:
  data-redis:
    driver: local
