FROM docker.io/ruby:3-slim-bookworm AS build

LABEL org.opencontainers.image.description="Chat rooms for LinuxFr"

LABEL org.opencontainers.image.title="Board for LinuxFr.org"
LABEL org.opencontainers.image.description="Users of the LinuxFr.org website can chat on a space called the board (« la tribune » in french). \
This Ruby daemon notifies the users when something is said with Server-Sent Event / EventSource."
LABEL org.opencontainers.image.source="https://github.com/linuxfrorg/board-sse-linuxfr.org"
LABEL org.opencontainers.image.url="https://github.com/linuxfrorg/board-sse-linuxfr.org"
LABEL org.opencontainers.image.licenses="AGPL-3.0-only"
LABEL org.opencontainers.image.version="ruby3-bookworm"
LABEL org.opencontainers.image.authors="Adrien Dorsaz <adrien@adorsaz.ch>"

ARG UID=1200

RUN \
  set -eux; \
  IFS=$'\n\t'; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    build-essential ruby ruby-dev; \
  apt-get clean;

USER ${UID}
WORKDIR /board-sse-linuxfr.org
ENV HOME=/board-sse-linuxfr.org

# Install board-sse-linuxfr.org
COPY --chown=${UID}:0 --chmod=770 . .
RUN gem build board-sse-linuxfr.org.gemspec

FROM build as production

RUN gem install ./board-sse-linuxfr.org-*.gem

# Clean development dependencies
USER 0
RUN apt purge --autoremove -y build-essential ruby-dev

USER ${UID}
EXPOSE 9000

CMD ["board-sse-linuxfr.org"]

